apiVersion: v1
kind: Namespace
metadata:
  name: cloudflare-ddns
  labels:
    name: cloudflare-ddns
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
